spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true        # SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # 보기 좋게 포맷
        use_sql_comments: true  # 쿼리 주석 표시
    hibernate:
      ddl-auto: update

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  token-validity-in-seconds: ${JWT_EXPIRATION_SECONDS}