version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: compiler-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_pass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  compiler:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      EXECUTION_WORK_DIR: /tmp/compiler-exec

      #테스트
#      DB_HOST: db
#      DB_PORT: 3306
#      DB_NAME: demo_db
#      DB_USER: demo_user
#      DB_PASSWORD: demo_pass

      # Actions에서 주입
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      # JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_SECONDS: ${JWT_EXPIRATION_SECONDS}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/compiler-exec:/tmp/compiler-exec

volumes:
  mysql-data: